import "../styles/globals.css";
import Layout from "../components/Layout";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from 'next/router'
import SplashScreen from "../components/SplashScreen";

function MyApp({ Component, pageProps }) {
  const [showChild, setShowChild] = useState(false);
  const [isLoading, setLoading] = useState(true)
  const { pathname } = useRouter()

  useEffect(() => {
    setShowChild(true);
  }, []);

  useEffect(() => {
    setLoading(true)
    setTimeout(() => setLoading(false), 1800);

  }, [pathname]);

  if (!showChild) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Majid Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? <SplashScreen /> : <Layout>
        <div className="py-8 sm:px-2 px-4 flex items-center min-h-screen h-full">
          <Component {...pageProps} />
        </div>
      </Layout>}
    </>
  );
}

export default MyApp;
