import "../styles/globals.css";
import Layout from "../components/Layout";
import Head from "next/head";
import { Suspense, useEffect,useState } from "react";

function MyApp({ Component, pageProps }) {
    const [showChild, setShowChild] = useState(false);
  useEffect(() => {
    setShowChild(true);
  }, []);

  if (!showChild) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Majid Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback="null">
        <Layout>
          <div className="py-8 px-4 flex items-center min-h-screen h-full">
            <Component {...pageProps} />
          </div>
        </Layout>
      </Suspense>
    </>
  );
}

export default MyApp;
