import Head from "next/head";
import useSoundCloud from "../hooks/useSoundCloud";
import styles from "../styles/Home.module.css";
import Landing from "./landing";

export default function Home() {
  const { iframeRef } = useSoundCloud()

  return (
    <div className={styles.container}>
      <Head>
        <title>Majid Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <iframe ref={iframeRef} id="sound-cloud-player" style={{
        border: 'none', height: 120, width: 400, position: "fixed",
        right: 16,
        top: 16
      }} allow="autoplay"
        src={"https://w.soundcloud.com/player/?url=https://soundcloud.com/aboveandbeyond/sets/we-are-all-we-need-1"}>
      </iframe>
      <Landing />
    </div>
  );
}

